better loop between menus, htpasswd options

diff --git a/htpasswd-manager b/htpasswd-manager
--- a/htpasswd-manager
+++ b/htpasswd-manager
@@ -1,10 +1,17 @@
 #!/bin/bash
 
-TEMP=$(getopt -o f:hv -l file:,help,verbose -- "$@")
+TEMP=$(getopt -o f:hvmBC:sp -l file:,help,verbose -- "$@")
 eval set -- $TEMP
 
 htpasswd="htpasswd"
 file=".htpasswd"
+
+## htpasswd options
+md5=0
+bcrypt=0
+cost=""
+sha=0
+plain=0
 : ${DIALOG=dialog}
 
 : ${DIALOG_OK=0}
@@ -15,6 +22,7 @@ file=".htpasswd"
 : ${DIALOG_ESC=255}
 
 
+htpasswdOptions=""
 while true
 do
     case "$1" in
@@ -31,6 +39,19 @@ do
             verbose=1
             shift
             ;;
+
+        ## options for htpasswd
+        -m|-B|-s|-p)
+            htpasswdOptions+="$1 "
+            shift
+            ;;
+        -C)
+            htpasswdOptions+="$1 $2"
+            shift 2
+            ;;
+
+        ## end options for htpasswd
+
         --)
             shift
             break
@@ -43,20 +64,6 @@ do
 done
 
 
-
-logins=""
-if [ -f $file ]
-then
-    echo "reading file"
-    logins=$(cat $file | cut -d: -f 1)
-
-    checklist=""
-    for login in $logins
-    do
-        checklist+=" $login $login"
-    done
-fi
-
 function add_login() {
     login=""
     password=""
@@ -66,12 +73,45 @@ function add_login() {
     "login" 1 1 "" 1 10 20 0 \
     "password" 2 1 "" 2 10 20 0 2>&1 1>&3
     )
-
+    r=$?
     exec 3>&-
+
+    echo "add login r: $r"
+    if [ $r -eq $DIALOG_CANCEL -o $r -eq $DIALOG_ESC ]
+    then
+        return 1
+    fi
+
     login=$(echo $v | cut -d' ' -f 1)
     password=$(echo $v | cut -d' ' -f 2)
 
-    htpasswd -b -c $file $login $password
+    echo "Adding $login - $password to $file"
+    options=""
+    if [ ! -f $file ]
+    then
+        options="-c"
+    fi
+    htpasswd $htpasswdOptions -b $options $file $login $password
+    ret=$?
+    if [ $ret -ne 0 ]
+    then
+        return 1
+    fi
+
+    return 0
+}
+
+function delete_login() {
+    loginToDelete=$1
+
+    htpasswd $htpasswdOptions -D $file $loginToDelete
+    ret=$?
+    if [ $ret -ne 0 ]
+    then
+        return 4
+    fi
+
+    return 0
 }
 
 function list_login() {
@@ -80,33 +120,68 @@ function list_login() {
         --extra-button \
         --extra-label "Delete" \
         --ok-label "Add" \
-        --visit-items \
+        --cancel-label "Exit" \
         --menu "Foo" 20 61 5 \
         $checklist 2> response
     r=$?
+        #--visit-items \
 
     if [ $r -eq 1 ]
     then
-        exit 0
+        return 1
     fi
 
     if [ $r -eq 0 ]
     then
         echo "adding passord"
+        add_login
     fi
 
     if [ $r -eq 3 ]
     then
-        echo "deleting password"
+        loginToDelete=$(cat response)
+        echo "deleting login $loginToDelete"
+        delete_login $loginToDelete
+        ret=$?
+        if [ $ret -ne 0 ]
+        then
+            echo "message box error"
+        fi
+
+        return $DIALOG_OK
     fi
 }
 
 appTitle="htpasswd manager"
-if [ $logins ]
-then
-    list_login $checklist
-else
-    add_login
-fi
 
+
+returnCode=0
+while [ $returnCode -ne 1 -a $returnCode -ne 250 ]
+do
+    logins=""
+    echo "Checking for $file"
+    if [ -f $file ]
+    then
+        echo "reading file"
+        logins=$(cat $file | cut -d: -f 1)
+
+        checklist=""
+        for login in $logins
+        do
+            checklist+=" $login $login"
+        done
+    else
+        echo "apparently $file is not found"
+    fi
+
+    if [ ! -z "$logins" ]
+    then
+        list_login $checklist
+        returnCode=$?
+    else
+        add_login
+        returnCode=$?
+    fi
+    echo "returncode: $returnCode"
+done
 #echo "r: $r - $(cat response)"
